name: Build & Run on RISC-V

on:
  workflow_dispatch:
  push:

jobs:
  build-and-run:
    runs-on: [self-hosted, Linux, RISCV64]
    permissions:
      contents: read

    steps:
      - name: Preflight | docker usable without sudo
        shell: bash
        run: docker version >/dev/null || { echo "Docker not ready"; exit 1; }

      - name: Preflight | ensure SECOND present
        shell: bash
        run: |
          if [ -z "${{ secrets.SECOND }}" ]; then
            echo "ERROR: Secret SECOND is empty or missing." >&2
            exit 1
          fi
          echo "OK: SECOND is set."

      - name: Write & validate SSH key
        shell: bash
        run: |
          umask 077
          mkdir -p ~/.ssh
          printf "%s\n" "${{ secrets.SECOND }}" > ~/.ssh/ci_rsa
          ssh-keygen -y -f ~/.ssh/ci_rsa >/dev/null \
            || { echo "ERROR: SECOND is not a valid OpenSSH private key"; exit 2; }
          echo "OK: SSH key format looks good."

      - name: Force SSH over 443 for GitHub
        shell: bash
        run: |
          cat >> ~/.ssh/config <<'EOF'
          Host github.com
            HostName ssh.github.com
            Port 443
            User git
            IdentityFile ~/.ssh/ci_rsa
            IdentitiesOnly yes
            StrictHostKeyChecking no
          EOF

      - name: Use SSH instead of HTTPS (and protocol v1)
        shell: bash
        run: |
          git config --global url."git@github.com:".insteadOf "https://github.com/"
          git config --global protocol.version 1

      - name: Preflight | git ls-remote over SSH:443
        shell: bash
        run: |
          git ls-remote git@github.com:${{ github.repository }}.git | head -n 5

      - name: Checkout repository (SSH on 443)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Verify checkout on host
        shell: bash
        run: |
          set -euo pipefail
          echo "GITHUB_WORKSPACE=${{ github.workspace }}"
          test -d "${{ github.workspace }}/.git" || { echo "ERROR: .git missing"; exit 1; }
          test -d "${{ github.workspace }}/deb2conda" || { echo "ERROR: deb2conda missing"; exit 1; }
          ls -la "${{ github.workspace }}" | head -n 80

      - name: Show runner info
        shell: bash
        run: |
          echo "Workspace: ${{ github.workspace }}"
          uname -a

      - name: Ensure docker buildx (user-space, no sudo)
        shell: bash
        run: |
          set -euo pipefail
          if ! docker buildx version >/dev/null 2>&1; then
          mkdir -p ~/.docker/cli-plugins
          BX_VER="v0.13.2"  # 版本可按需改
          arch="$(uname -m)"
          case "$arch" in
           riscv64)  bx_asset="buildx-${BX_VER}.linux-riscv64" ;;
           aarch64|arm64) bx_asset="buildx-${BX_VER}.linux-arm64" ;;
           x86_64|amd64)  bx_asset="buildx-${BX_VER}.linux-amd64" ;;
           *) echo "Unsupported arch: $arch"; exit 1 ;;
           esac
           curl -L --fail \
             "https://github.com/docker/buildx/releases/download/${BX_VER}/${bx_asset}" \
            -o ~/.docker/cli-plugins/docker-buildx
            chmod +x ~/.docker/cli-plugins/docker-buildx
          fi
          docker buildx version


      
      # ---- 无 sudo：用用户可写缓存目录 ----
      - name: Prepare Docker build cache dir (no sudo)
        shell: bash
        run: |
          CACHE_DIR="$HOME/.cache/docker-buildx"
          mkdir -p "$CACHE_DIR"
          echo "CACHE_DIR=$CACHE_DIR" >> "$GITHUB_ENV"

      - name: Docker build (with persistent cache, no sudo)
        shell: bash
        env:
          DOCKER_BUILDKIT: "1"
        run: |
          set -euo pipefail
          docker buildx create --use --name mamba-builder 2>/dev/null || docker buildx use mamba-builder
          docker buildx inspect --bootstrap

          IMAGE_TAG="local/mamba-riscv64:${{ github.sha }}"
          CACHE_DIR="${CACHE_DIR:-$HOME/.cache/docker-buildx}"

          docker buildx build --load \
            -t "$IMAGE_TAG" \
            -t local/mamba-riscv64:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from=type=local,src="$CACHE_DIR" \
            --cache-to=type=local,dest="$CACHE_DIR",mode=max \
            .

          echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_ENV"
          echo "IMAGE_ID=$(docker images -q "$IMAGE_TAG")" >> "$GITHUB_ENV"

      - name: Verify image built
        shell: bash
        run: |
          set -euo pipefail
          test -n "${IMAGE_TAG:-}" && test -n "${IMAGE_ID:-}" || { echo "IMAGE envs missing"; exit 1; }
          docker image inspect "$IMAGE_TAG" >/dev/null
          echo "OK: $IMAGE_TAG exists ($IMAGE_ID)"

      - name: Create local conda channel dirs (on host)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "${{ github.workspace }}/local-conda-channel/linux-riscv64" \
                   "${{ github.workspace }}/local-conda-channel/noarch"
          ls -al "${{ github.workspace }}/local-conda-channel"

      - name: Run container with repo mounted at /workspace
        shell: bash
        run: |
          set -euo pipefail
          echo "Using image: $IMAGE_TAG (id: $IMAGE_ID)"
          docker run --rm \
            -v "${{ github.workspace }}:/workspace:rw" \
            -w /workspace \
            -e LOCAL_CHANNEL="file:///workspace/local-conda-channel" \
            "$IMAGE_TAG" \
            bash -lc '
              set -euo pipefail
              echo "pwd: $(pwd)"
              test -d /workspace/deb2conda || { echo "ERROR: /workspace/deb2conda missing"; exit 1; }
              ls -la /workspace | head -n 80
              ls -la /workspace/local-conda-channel
              echo "LOCAL_CHANNEL=$LOCAL_CHANNEL"
              echo "container OK"
            '
